title = 'MVTHS Golf Cart'

label = 'EN'
locale = 'en-US'

copyright = 'All rights reserved'

weight = 1


[params]
    author = 'MVTHS Engineering'
    bio = '"The only sure rule in golf is... he who has the fastest cart never has to play the bad lie."'






