[[main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[[main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

[[main]]
    name = 'Document'
    pageRef = '/document'
    weight = 30

[[main]]
    name = 'Sunk Robotics'
    pageRef = 'https://www.sunkrobotics.com/'
    weight = 40

[[main]]
    name = 'MVTHS Engineering'
    pageRef = 'https://mvthsengineering.com/'
    weight = 50

